# Generated by Django 3.1.7 on 2021-05-15 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('captain', models.CharField(max_length=50)),
                ('logo_url', models.ImageField(upload_to='')),
                ('state', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('statistics_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('played', models.DecimalField(decimal_places=0, max_digits=5)),
                ('won', models.DecimalField(decimal_places=0, max_digits=5)),
                ('lost', models.DecimalField(decimal_places=0, max_digits=5)),
                ('tied', models.DecimalField(decimal_places=0, max_digits=5)),
                ('points', models.DecimalField(decimal_places=0, max_digits=5)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl.team')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('jersey_id', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
                ('played', models.IntegerField(max_length=100)),
                ('runs', models.DecimalField(decimal_places=0, max_digits=5)),
                ('max_runs', models.IntegerField(max_length=100)),
                ('fifties', models.IntegerField(max_length=100)),
                ('hundreds', models.IntegerField(max_length=100)),
                ('wickets', models.DecimalField(decimal_places=0, max_digits=5)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipl.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.DecimalField(decimal_places=0, max_digits=2, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('team1_score', models.CharField(blank=True, max_length=50, null=True)),
                ('team2_score', models.CharField(blank=True, max_length=50, null=True)),
                ('team1_overs', models.CharField(blank=True, max_length=50, null=True)),
                ('team2_overs', models.CharField(blank=True, max_length=50, null=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_one', to='ipl.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_two', to='ipl.team')),
            ],
        ),
    ]
