# Generated by Django 3.1.7 on 2021-05-15 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image_url',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
