# Generated by Django 3.1.7 on 2021-05-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipl', '0002_player_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='image_url',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ipl.team'),
        ),
    ]
